export const EVENT_TYPES = Object.freeze({
    GAME_START: 'GAME_START',
    GAME_END: 'GAME_END',
    PLAYER_MOVE: 'PLAYER_MOVE',
    PLAYER_SHOT: 'PLAYER_SHOT',
    PLAYER_HIT: 'PLAYER_HIT',
    ENEMY_DESTROYED: 'ENEMY_DESTROYED',
    SCORE_UPDATED: 'SCORE_UPDATED',
    TIMER_UPDATED: 'TIMER_UPDATED'
})
