apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: airflow-webserver
          image: space-invaders-airflow:latest
          imagePullPolicy: IfNotPresent
          command: ["airflow", "api-server"]
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secret
          ports:
            - containerPort: 8080
